// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dstgo/lobby/server/data/ent/predicate"
	"github.com/dstgo/lobby/server/data/ent/secondary"
	"github.com/dstgo/lobby/server/data/ent/server"
)

// SecondaryQuery is the builder for querying Secondary entities.
type SecondaryQuery struct {
	config
	ctx         *QueryContext
	order       []secondary.OrderOption
	inters      []Interceptor
	predicates  []predicate.Secondary
	withServers *ServerQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SecondaryQuery builder.
func (sq *SecondaryQuery) Where(ps ...predicate.Secondary) *SecondaryQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *SecondaryQuery) Limit(limit int) *SecondaryQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *SecondaryQuery) Offset(offset int) *SecondaryQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SecondaryQuery) Unique(unique bool) *SecondaryQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *SecondaryQuery) Order(o ...secondary.OrderOption) *SecondaryQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryServers chains the current query on the "servers" edge.
func (sq *SecondaryQuery) QueryServers() *ServerQuery {
	query := (&ServerClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(secondary.Table, secondary.FieldID, selector),
			sqlgraph.To(server.Table, server.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, secondary.ServersTable, secondary.ServersColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Secondary entity from the query.
// Returns a *NotFoundError when no Secondary was found.
func (sq *SecondaryQuery) First(ctx context.Context) (*Secondary, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{secondary.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SecondaryQuery) FirstX(ctx context.Context) *Secondary {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Secondary ID from the query.
// Returns a *NotFoundError when no Secondary ID was found.
func (sq *SecondaryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{secondary.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SecondaryQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Secondary entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Secondary entity is found.
// Returns a *NotFoundError when no Secondary entities are found.
func (sq *SecondaryQuery) Only(ctx context.Context) (*Secondary, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{secondary.Label}
	default:
		return nil, &NotSingularError{secondary.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SecondaryQuery) OnlyX(ctx context.Context) *Secondary {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Secondary ID in the query.
// Returns a *NotSingularError when more than one Secondary ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SecondaryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{secondary.Label}
	default:
		err = &NotSingularError{secondary.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SecondaryQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Secondaries.
func (sq *SecondaryQuery) All(ctx context.Context) ([]*Secondary, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryAll)
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Secondary, *SecondaryQuery]()
	return withInterceptors[[]*Secondary](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *SecondaryQuery) AllX(ctx context.Context) []*Secondary {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Secondary IDs.
func (sq *SecondaryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryIDs)
	if err = sq.Select(secondary.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SecondaryQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SecondaryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryCount)
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*SecondaryQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SecondaryQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SecondaryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryExist)
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SecondaryQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SecondaryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SecondaryQuery) Clone() *SecondaryQuery {
	if sq == nil {
		return nil
	}
	return &SecondaryQuery{
		config:      sq.config,
		ctx:         sq.ctx.Clone(),
		order:       append([]secondary.OrderOption{}, sq.order...),
		inters:      append([]Interceptor{}, sq.inters...),
		predicates:  append([]predicate.Secondary{}, sq.predicates...),
		withServers: sq.withServers.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithServers tells the query-builder to eager-load the nodes that are connected to
// the "servers" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SecondaryQuery) WithServers(opts ...func(*ServerQuery)) *SecondaryQuery {
	query := (&ServerClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withServers = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Sid string `json:"sid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Secondary.Query().
//		GroupBy(secondary.FieldSid).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SecondaryQuery) GroupBy(field string, fields ...string) *SecondaryGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SecondaryGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = secondary.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Sid string `json:"sid,omitempty"`
//	}
//
//	client.Secondary.Query().
//		Select(secondary.FieldSid).
//		Scan(ctx, &v)
func (sq *SecondaryQuery) Select(fields ...string) *SecondarySelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &SecondarySelect{SecondaryQuery: sq}
	sbuild.label = secondary.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SecondarySelect configured with the given aggregations.
func (sq *SecondaryQuery) Aggregate(fns ...AggregateFunc) *SecondarySelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SecondaryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !secondary.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SecondaryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Secondary, error) {
	var (
		nodes       = []*Secondary{}
		_spec       = sq.querySpec()
		loadedTypes = [1]bool{
			sq.withServers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Secondary).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Secondary{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withServers; query != nil {
		if err := sq.loadServers(ctx, query, nodes, nil,
			func(n *Secondary, e *Server) { n.Edges.Servers = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SecondaryQuery) loadServers(ctx context.Context, query *ServerQuery, nodes []*Secondary, init func(*Secondary), assign func(*Secondary, *Server)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Secondary)
	for i := range nodes {
		fk := nodes[i].OwnerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(server.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "owner_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (sq *SecondaryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SecondaryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(secondary.Table, secondary.Columns, sqlgraph.NewFieldSpec(secondary.FieldID, field.TypeInt))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, secondary.FieldID)
		for i := range fields {
			if fields[i] != secondary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if sq.withServers != nil {
			_spec.Node.AddColumnOnce(secondary.FieldOwnerID)
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SecondaryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(secondary.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = secondary.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SecondaryGroupBy is the group-by builder for Secondary entities.
type SecondaryGroupBy struct {
	selector
	build *SecondaryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SecondaryGroupBy) Aggregate(fns ...AggregateFunc) *SecondaryGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *SecondaryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, ent.OpQueryGroupBy)
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SecondaryQuery, *SecondaryGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *SecondaryGroupBy) sqlScan(ctx context.Context, root *SecondaryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SecondarySelect is the builder for selecting fields of Secondary entities.
type SecondarySelect struct {
	*SecondaryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SecondarySelect) Aggregate(fns ...AggregateFunc) *SecondarySelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SecondarySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, ent.OpQuerySelect)
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SecondaryQuery, *SecondarySelect](ctx, ss.SecondaryQuery, ss, ss.inters, v)
}

func (ss *SecondarySelect) sqlScan(ctx context.Context, root *SecondaryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
