// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dstgo/lobby/server/data/ent/predicate"
	"github.com/dstgo/lobby/server/data/ent/secondary"
)

// SecondaryDelete is the builder for deleting a Secondary entity.
type SecondaryDelete struct {
	config
	hooks    []Hook
	mutation *SecondaryMutation
}

// Where appends a list predicates to the SecondaryDelete builder.
func (sd *SecondaryDelete) Where(ps ...predicate.Secondary) *SecondaryDelete {
	sd.mutation.Where(ps...)
	return sd
}

// Limit the number of records to be returned by this query.
func (sd *SecondaryDelete) Limit(limit int) *SecondaryDelete {
	sd.ctx.Limit = &limit
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *SecondaryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sd.sqlExec, sd.mutation, sd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *SecondaryDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *SecondaryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(secondary.Table, sqlgraph.NewFieldSpec(secondary.FieldID, field.TypeInt))
	if ps := sd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sd.mutation.done = true
	return affected, err
}

// SecondaryDeleteOne is the builder for deleting a single Secondary entity.
type SecondaryDeleteOne struct {
	sd *SecondaryDelete
}

// Where appends a list predicates to the SecondaryDelete builder.
func (sdo *SecondaryDeleteOne) Where(ps ...predicate.Secondary) *SecondaryDeleteOne {
	sdo.sd.mutation.Where(ps...)
	return sdo
}

// Exec executes the deletion query.
func (sdo *SecondaryDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{secondary.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *SecondaryDeleteOne) ExecX(ctx context.Context) {
	if err := sdo.Exec(ctx); err != nil {
		panic(err)
	}
}
