// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dstgo/lobby/server/data/ent/secondary"
	"github.com/dstgo/lobby/server/data/ent/server"
)

// SecondaryCreate is the builder for creating a Secondary entity.
type SecondaryCreate struct {
	config
	mutation *SecondaryMutation
	hooks    []Hook
}

// SetSid sets the "sid" field.
func (sc *SecondaryCreate) SetSid(s string) *SecondaryCreate {
	sc.mutation.SetSid(s)
	return sc
}

// SetSteamID sets the "steam_id" field.
func (sc *SecondaryCreate) SetSteamID(s string) *SecondaryCreate {
	sc.mutation.SetSteamID(s)
	return sc
}

// SetAddress sets the "address" field.
func (sc *SecondaryCreate) SetAddress(s string) *SecondaryCreate {
	sc.mutation.SetAddress(s)
	return sc
}

// SetPort sets the "port" field.
func (sc *SecondaryCreate) SetPort(i int) *SecondaryCreate {
	sc.mutation.SetPort(i)
	return sc
}

// SetOwnerID sets the "owner_id" field.
func (sc *SecondaryCreate) SetOwnerID(i int) *SecondaryCreate {
	sc.mutation.SetOwnerID(i)
	return sc
}

// SetServersID sets the "servers" edge to the Server entity by ID.
func (sc *SecondaryCreate) SetServersID(id int) *SecondaryCreate {
	sc.mutation.SetServersID(id)
	return sc
}

// SetServers sets the "servers" edge to the Server entity.
func (sc *SecondaryCreate) SetServers(s *Server) *SecondaryCreate {
	return sc.SetServersID(s.ID)
}

// Mutation returns the SecondaryMutation object of the builder.
func (sc *SecondaryCreate) Mutation() *SecondaryMutation {
	return sc.mutation
}

// Save creates the Secondary in the database.
func (sc *SecondaryCreate) Save(ctx context.Context) (*Secondary, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SecondaryCreate) SaveX(ctx context.Context) *Secondary {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SecondaryCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SecondaryCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SecondaryCreate) check() error {
	if _, ok := sc.mutation.Sid(); !ok {
		return &ValidationError{Name: "sid", err: errors.New(`ent: missing required field "Secondary.sid"`)}
	}
	if _, ok := sc.mutation.SteamID(); !ok {
		return &ValidationError{Name: "steam_id", err: errors.New(`ent: missing required field "Secondary.steam_id"`)}
	}
	if _, ok := sc.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Secondary.address"`)}
	}
	if _, ok := sc.mutation.Port(); !ok {
		return &ValidationError{Name: "port", err: errors.New(`ent: missing required field "Secondary.port"`)}
	}
	if _, ok := sc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Secondary.owner_id"`)}
	}
	if len(sc.mutation.ServersIDs()) == 0 {
		return &ValidationError{Name: "servers", err: errors.New(`ent: missing required edge "Secondary.servers"`)}
	}
	return nil
}

func (sc *SecondaryCreate) sqlSave(ctx context.Context) (*Secondary, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SecondaryCreate) createSpec() (*Secondary, *sqlgraph.CreateSpec) {
	var (
		_node = &Secondary{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(secondary.Table, sqlgraph.NewFieldSpec(secondary.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Sid(); ok {
		_spec.SetField(secondary.FieldSid, field.TypeString, value)
		_node.Sid = value
	}
	if value, ok := sc.mutation.SteamID(); ok {
		_spec.SetField(secondary.FieldSteamID, field.TypeString, value)
		_node.SteamID = value
	}
	if value, ok := sc.mutation.Address(); ok {
		_spec.SetField(secondary.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := sc.mutation.Port(); ok {
		_spec.SetField(secondary.FieldPort, field.TypeInt, value)
		_node.Port = value
	}
	if nodes := sc.mutation.ServersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   secondary.ServersTable,
			Columns: []string{secondary.ServersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SecondaryCreateBulk is the builder for creating many Secondary entities in bulk.
type SecondaryCreateBulk struct {
	config
	err      error
	builders []*SecondaryCreate
}

// Save creates the Secondary entities in the database.
func (scb *SecondaryCreateBulk) Save(ctx context.Context) ([]*Secondary, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Secondary, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SecondaryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SecondaryCreateBulk) SaveX(ctx context.Context) []*Secondary {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SecondaryCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SecondaryCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
