// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dstgo/lobby/server/data/ent/secondary"
	"github.com/dstgo/lobby/server/data/ent/server"
	"github.com/dstgo/lobby/server/data/ent/tag"
)

// ServerCreate is the builder for creating a Server entity.
type ServerCreate struct {
	config
	mutation *ServerMutation
	hooks    []Hook
}

// SetGUID sets the "guid" field.
func (sc *ServerCreate) SetGUID(s string) *ServerCreate {
	sc.mutation.SetGUID(s)
	return sc
}

// SetRowID sets the "row_id" field.
func (sc *ServerCreate) SetRowID(s string) *ServerCreate {
	sc.mutation.SetRowID(s)
	return sc
}

// SetSteamID sets the "steam_id" field.
func (sc *ServerCreate) SetSteamID(s string) *ServerCreate {
	sc.mutation.SetSteamID(s)
	return sc
}

// SetSteamClanID sets the "steam_clan_id" field.
func (sc *ServerCreate) SetSteamClanID(s string) *ServerCreate {
	sc.mutation.SetSteamClanID(s)
	return sc
}

// SetOwnerID sets the "owner_id" field.
func (sc *ServerCreate) SetOwnerID(s string) *ServerCreate {
	sc.mutation.SetOwnerID(s)
	return sc
}

// SetSteamRoom sets the "steam_room" field.
func (sc *ServerCreate) SetSteamRoom(s string) *ServerCreate {
	sc.mutation.SetSteamRoom(s)
	return sc
}

// SetSession sets the "session" field.
func (sc *ServerCreate) SetSession(s string) *ServerCreate {
	sc.mutation.SetSession(s)
	return sc
}

// SetAddress sets the "address" field.
func (sc *ServerCreate) SetAddress(s string) *ServerCreate {
	sc.mutation.SetAddress(s)
	return sc
}

// SetPort sets the "port" field.
func (sc *ServerCreate) SetPort(i int) *ServerCreate {
	sc.mutation.SetPort(i)
	return sc
}

// SetHost sets the "host" field.
func (sc *ServerCreate) SetHost(s string) *ServerCreate {
	sc.mutation.SetHost(s)
	return sc
}

// SetPlatform sets the "platform" field.
func (sc *ServerCreate) SetPlatform(s string) *ServerCreate {
	sc.mutation.SetPlatform(s)
	return sc
}

// SetClanOnly sets the "clan_only" field.
func (sc *ServerCreate) SetClanOnly(b bool) *ServerCreate {
	sc.mutation.SetClanOnly(b)
	return sc
}

// SetLanOnly sets the "lan_only" field.
func (sc *ServerCreate) SetLanOnly(b bool) *ServerCreate {
	sc.mutation.SetLanOnly(b)
	return sc
}

// SetName sets the "name" field.
func (sc *ServerCreate) SetName(s string) *ServerCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetGameMode sets the "game_mode" field.
func (sc *ServerCreate) SetGameMode(s string) *ServerCreate {
	sc.mutation.SetGameMode(s)
	return sc
}

// SetIntent sets the "intent" field.
func (sc *ServerCreate) SetIntent(s string) *ServerCreate {
	sc.mutation.SetIntent(s)
	return sc
}

// SetSeason sets the "season" field.
func (sc *ServerCreate) SetSeason(s string) *ServerCreate {
	sc.mutation.SetSeason(s)
	return sc
}

// SetVersion sets the "version" field.
func (sc *ServerCreate) SetVersion(i int) *ServerCreate {
	sc.mutation.SetVersion(i)
	return sc
}

// SetMaxOnline sets the "max_online" field.
func (sc *ServerCreate) SetMaxOnline(i int) *ServerCreate {
	sc.mutation.SetMaxOnline(i)
	return sc
}

// SetOnline sets the "online" field.
func (sc *ServerCreate) SetOnline(i int) *ServerCreate {
	sc.mutation.SetOnline(i)
	return sc
}

// SetLevel sets the "level" field.
func (sc *ServerCreate) SetLevel(i int) *ServerCreate {
	sc.mutation.SetLevel(i)
	return sc
}

// SetMod sets the "mod" field.
func (sc *ServerCreate) SetMod(b bool) *ServerCreate {
	sc.mutation.SetMod(b)
	return sc
}

// SetPvp sets the "pvp" field.
func (sc *ServerCreate) SetPvp(b bool) *ServerCreate {
	sc.mutation.SetPvp(b)
	return sc
}

// SetPassword sets the "password" field.
func (sc *ServerCreate) SetPassword(b bool) *ServerCreate {
	sc.mutation.SetPassword(b)
	return sc
}

// SetDedicated sets the "dedicated" field.
func (sc *ServerCreate) SetDedicated(b bool) *ServerCreate {
	sc.mutation.SetDedicated(b)
	return sc
}

// SetClientHosted sets the "client_hosted" field.
func (sc *ServerCreate) SetClientHosted(b bool) *ServerCreate {
	sc.mutation.SetClientHosted(b)
	return sc
}

// SetAllowNewPlayers sets the "allow_new_players" field.
func (sc *ServerCreate) SetAllowNewPlayers(b bool) *ServerCreate {
	sc.mutation.SetAllowNewPlayers(b)
	return sc
}

// SetServerPaused sets the "server_paused" field.
func (sc *ServerCreate) SetServerPaused(b bool) *ServerCreate {
	sc.mutation.SetServerPaused(b)
	return sc
}

// SetFriendOnly sets the "friend_only" field.
func (sc *ServerCreate) SetFriendOnly(b bool) *ServerCreate {
	sc.mutation.SetFriendOnly(b)
	return sc
}

// SetQueryVersion sets the "query_version" field.
func (sc *ServerCreate) SetQueryVersion(i int64) *ServerCreate {
	sc.mutation.SetQueryVersion(i)
	return sc
}

// SetCountry sets the "country" field.
func (sc *ServerCreate) SetCountry(s string) *ServerCreate {
	sc.mutation.SetCountry(s)
	return sc
}

// SetContinent sets the "continent" field.
func (sc *ServerCreate) SetContinent(s string) *ServerCreate {
	sc.mutation.SetContinent(s)
	return sc
}

// SetCountryCode sets the "country_code" field.
func (sc *ServerCreate) SetCountryCode(s string) *ServerCreate {
	sc.mutation.SetCountryCode(s)
	return sc
}

// SetCity sets the "city" field.
func (sc *ServerCreate) SetCity(s string) *ServerCreate {
	sc.mutation.SetCity(s)
	return sc
}

// SetRegion sets the "region" field.
func (sc *ServerCreate) SetRegion(s string) *ServerCreate {
	sc.mutation.SetRegion(s)
	return sc
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (sc *ServerCreate) AddTagIDs(ids ...int) *ServerCreate {
	sc.mutation.AddTagIDs(ids...)
	return sc
}

// AddTags adds the "tags" edges to the Tag entity.
func (sc *ServerCreate) AddTags(t ...*Tag) *ServerCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return sc.AddTagIDs(ids...)
}

// AddSecondaryIDs adds the "secondaries" edge to the Secondary entity by IDs.
func (sc *ServerCreate) AddSecondaryIDs(ids ...int) *ServerCreate {
	sc.mutation.AddSecondaryIDs(ids...)
	return sc
}

// AddSecondaries adds the "secondaries" edges to the Secondary entity.
func (sc *ServerCreate) AddSecondaries(s ...*Secondary) *ServerCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddSecondaryIDs(ids...)
}

// Mutation returns the ServerMutation object of the builder.
func (sc *ServerCreate) Mutation() *ServerMutation {
	return sc.mutation
}

// Save creates the Server in the database.
func (sc *ServerCreate) Save(ctx context.Context) (*Server, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *ServerCreate) SaveX(ctx context.Context) *Server {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *ServerCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *ServerCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *ServerCreate) check() error {
	if _, ok := sc.mutation.GUID(); !ok {
		return &ValidationError{Name: "guid", err: errors.New(`ent: missing required field "Server.guid"`)}
	}
	if _, ok := sc.mutation.RowID(); !ok {
		return &ValidationError{Name: "row_id", err: errors.New(`ent: missing required field "Server.row_id"`)}
	}
	if _, ok := sc.mutation.SteamID(); !ok {
		return &ValidationError{Name: "steam_id", err: errors.New(`ent: missing required field "Server.steam_id"`)}
	}
	if _, ok := sc.mutation.SteamClanID(); !ok {
		return &ValidationError{Name: "steam_clan_id", err: errors.New(`ent: missing required field "Server.steam_clan_id"`)}
	}
	if _, ok := sc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Server.owner_id"`)}
	}
	if _, ok := sc.mutation.SteamRoom(); !ok {
		return &ValidationError{Name: "steam_room", err: errors.New(`ent: missing required field "Server.steam_room"`)}
	}
	if _, ok := sc.mutation.Session(); !ok {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required field "Server.session"`)}
	}
	if _, ok := sc.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Server.address"`)}
	}
	if _, ok := sc.mutation.Port(); !ok {
		return &ValidationError{Name: "port", err: errors.New(`ent: missing required field "Server.port"`)}
	}
	if _, ok := sc.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "Server.host"`)}
	}
	if _, ok := sc.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Server.platform"`)}
	}
	if _, ok := sc.mutation.ClanOnly(); !ok {
		return &ValidationError{Name: "clan_only", err: errors.New(`ent: missing required field "Server.clan_only"`)}
	}
	if _, ok := sc.mutation.LanOnly(); !ok {
		return &ValidationError{Name: "lan_only", err: errors.New(`ent: missing required field "Server.lan_only"`)}
	}
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Server.name"`)}
	}
	if _, ok := sc.mutation.GameMode(); !ok {
		return &ValidationError{Name: "game_mode", err: errors.New(`ent: missing required field "Server.game_mode"`)}
	}
	if _, ok := sc.mutation.Intent(); !ok {
		return &ValidationError{Name: "intent", err: errors.New(`ent: missing required field "Server.intent"`)}
	}
	if _, ok := sc.mutation.Season(); !ok {
		return &ValidationError{Name: "season", err: errors.New(`ent: missing required field "Server.season"`)}
	}
	if _, ok := sc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Server.version"`)}
	}
	if _, ok := sc.mutation.MaxOnline(); !ok {
		return &ValidationError{Name: "max_online", err: errors.New(`ent: missing required field "Server.max_online"`)}
	}
	if _, ok := sc.mutation.Online(); !ok {
		return &ValidationError{Name: "online", err: errors.New(`ent: missing required field "Server.online"`)}
	}
	if _, ok := sc.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "Server.level"`)}
	}
	if _, ok := sc.mutation.Mod(); !ok {
		return &ValidationError{Name: "mod", err: errors.New(`ent: missing required field "Server.mod"`)}
	}
	if _, ok := sc.mutation.Pvp(); !ok {
		return &ValidationError{Name: "pvp", err: errors.New(`ent: missing required field "Server.pvp"`)}
	}
	if _, ok := sc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "Server.password"`)}
	}
	if _, ok := sc.mutation.Dedicated(); !ok {
		return &ValidationError{Name: "dedicated", err: errors.New(`ent: missing required field "Server.dedicated"`)}
	}
	if _, ok := sc.mutation.ClientHosted(); !ok {
		return &ValidationError{Name: "client_hosted", err: errors.New(`ent: missing required field "Server.client_hosted"`)}
	}
	if _, ok := sc.mutation.AllowNewPlayers(); !ok {
		return &ValidationError{Name: "allow_new_players", err: errors.New(`ent: missing required field "Server.allow_new_players"`)}
	}
	if _, ok := sc.mutation.ServerPaused(); !ok {
		return &ValidationError{Name: "server_paused", err: errors.New(`ent: missing required field "Server.server_paused"`)}
	}
	if _, ok := sc.mutation.FriendOnly(); !ok {
		return &ValidationError{Name: "friend_only", err: errors.New(`ent: missing required field "Server.friend_only"`)}
	}
	if _, ok := sc.mutation.QueryVersion(); !ok {
		return &ValidationError{Name: "query_version", err: errors.New(`ent: missing required field "Server.query_version"`)}
	}
	if _, ok := sc.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "Server.country"`)}
	}
	if _, ok := sc.mutation.Continent(); !ok {
		return &ValidationError{Name: "continent", err: errors.New(`ent: missing required field "Server.continent"`)}
	}
	if _, ok := sc.mutation.CountryCode(); !ok {
		return &ValidationError{Name: "country_code", err: errors.New(`ent: missing required field "Server.country_code"`)}
	}
	if _, ok := sc.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "Server.city"`)}
	}
	if _, ok := sc.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "Server.region"`)}
	}
	return nil
}

func (sc *ServerCreate) sqlSave(ctx context.Context) (*Server, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *ServerCreate) createSpec() (*Server, *sqlgraph.CreateSpec) {
	var (
		_node = &Server{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(server.Table, sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.GUID(); ok {
		_spec.SetField(server.FieldGUID, field.TypeString, value)
		_node.GUID = value
	}
	if value, ok := sc.mutation.RowID(); ok {
		_spec.SetField(server.FieldRowID, field.TypeString, value)
		_node.RowID = value
	}
	if value, ok := sc.mutation.SteamID(); ok {
		_spec.SetField(server.FieldSteamID, field.TypeString, value)
		_node.SteamID = value
	}
	if value, ok := sc.mutation.SteamClanID(); ok {
		_spec.SetField(server.FieldSteamClanID, field.TypeString, value)
		_node.SteamClanID = value
	}
	if value, ok := sc.mutation.OwnerID(); ok {
		_spec.SetField(server.FieldOwnerID, field.TypeString, value)
		_node.OwnerID = value
	}
	if value, ok := sc.mutation.SteamRoom(); ok {
		_spec.SetField(server.FieldSteamRoom, field.TypeString, value)
		_node.SteamRoom = value
	}
	if value, ok := sc.mutation.Session(); ok {
		_spec.SetField(server.FieldSession, field.TypeString, value)
		_node.Session = value
	}
	if value, ok := sc.mutation.Address(); ok {
		_spec.SetField(server.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := sc.mutation.Port(); ok {
		_spec.SetField(server.FieldPort, field.TypeInt, value)
		_node.Port = value
	}
	if value, ok := sc.mutation.Host(); ok {
		_spec.SetField(server.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := sc.mutation.Platform(); ok {
		_spec.SetField(server.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := sc.mutation.ClanOnly(); ok {
		_spec.SetField(server.FieldClanOnly, field.TypeBool, value)
		_node.ClanOnly = value
	}
	if value, ok := sc.mutation.LanOnly(); ok {
		_spec.SetField(server.FieldLanOnly, field.TypeBool, value)
		_node.LanOnly = value
	}
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(server.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.GameMode(); ok {
		_spec.SetField(server.FieldGameMode, field.TypeString, value)
		_node.GameMode = value
	}
	if value, ok := sc.mutation.Intent(); ok {
		_spec.SetField(server.FieldIntent, field.TypeString, value)
		_node.Intent = value
	}
	if value, ok := sc.mutation.Season(); ok {
		_spec.SetField(server.FieldSeason, field.TypeString, value)
		_node.Season = value
	}
	if value, ok := sc.mutation.Version(); ok {
		_spec.SetField(server.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := sc.mutation.MaxOnline(); ok {
		_spec.SetField(server.FieldMaxOnline, field.TypeInt, value)
		_node.MaxOnline = value
	}
	if value, ok := sc.mutation.Online(); ok {
		_spec.SetField(server.FieldOnline, field.TypeInt, value)
		_node.Online = value
	}
	if value, ok := sc.mutation.Level(); ok {
		_spec.SetField(server.FieldLevel, field.TypeInt, value)
		_node.Level = value
	}
	if value, ok := sc.mutation.Mod(); ok {
		_spec.SetField(server.FieldMod, field.TypeBool, value)
		_node.Mod = value
	}
	if value, ok := sc.mutation.Pvp(); ok {
		_spec.SetField(server.FieldPvp, field.TypeBool, value)
		_node.Pvp = value
	}
	if value, ok := sc.mutation.Password(); ok {
		_spec.SetField(server.FieldPassword, field.TypeBool, value)
		_node.Password = value
	}
	if value, ok := sc.mutation.Dedicated(); ok {
		_spec.SetField(server.FieldDedicated, field.TypeBool, value)
		_node.Dedicated = value
	}
	if value, ok := sc.mutation.ClientHosted(); ok {
		_spec.SetField(server.FieldClientHosted, field.TypeBool, value)
		_node.ClientHosted = value
	}
	if value, ok := sc.mutation.AllowNewPlayers(); ok {
		_spec.SetField(server.FieldAllowNewPlayers, field.TypeBool, value)
		_node.AllowNewPlayers = value
	}
	if value, ok := sc.mutation.ServerPaused(); ok {
		_spec.SetField(server.FieldServerPaused, field.TypeBool, value)
		_node.ServerPaused = value
	}
	if value, ok := sc.mutation.FriendOnly(); ok {
		_spec.SetField(server.FieldFriendOnly, field.TypeBool, value)
		_node.FriendOnly = value
	}
	if value, ok := sc.mutation.QueryVersion(); ok {
		_spec.SetField(server.FieldQueryVersion, field.TypeInt64, value)
		_node.QueryVersion = value
	}
	if value, ok := sc.mutation.Country(); ok {
		_spec.SetField(server.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := sc.mutation.Continent(); ok {
		_spec.SetField(server.FieldContinent, field.TypeString, value)
		_node.Continent = value
	}
	if value, ok := sc.mutation.CountryCode(); ok {
		_spec.SetField(server.FieldCountryCode, field.TypeString, value)
		_node.CountryCode = value
	}
	if value, ok := sc.mutation.City(); ok {
		_spec.SetField(server.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := sc.mutation.Region(); ok {
		_spec.SetField(server.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if nodes := sc.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.TagsTable,
			Columns: []string{server.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.SecondariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   server.SecondariesTable,
			Columns: []string{server.SecondariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secondary.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ServerCreateBulk is the builder for creating many Server entities in bulk.
type ServerCreateBulk struct {
	config
	err      error
	builders []*ServerCreate
}

// Save creates the Server entities in the database.
func (scb *ServerCreateBulk) Save(ctx context.Context) ([]*Server, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Server, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *ServerCreateBulk) SaveX(ctx context.Context) []*Server {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *ServerCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *ServerCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
