// Code generated by ent, DO NOT EDIT.

package ent

func (sc *SecondaryCreate) SetSecondary(input *Secondary) *SecondaryCreate {
	sc.SetSid(input.Sid)
	sc.SetSteamID(input.SteamID)
	sc.SetAddress(input.Address)
	sc.SetPort(input.Port)
	sc.SetOwnerID(input.OwnerID)
	return sc
}

func (sc *ServerCreate) SetServer(input *Server) *ServerCreate {
	sc.SetGUID(input.GUID)
	sc.SetRowID(input.RowID)
	sc.SetSteamID(input.SteamID)
	sc.SetSteamClanID(input.SteamClanID)
	sc.SetOwnerID(input.OwnerID)
	sc.SetSteamRoom(input.SteamRoom)
	sc.SetSession(input.Session)
	sc.SetAddress(input.Address)
	sc.SetPort(input.Port)
	sc.SetHost(input.Host)
	sc.SetPlatform(input.Platform)
	sc.SetClanOnly(input.ClanOnly)
	sc.SetLanOnly(input.LanOnly)
	sc.SetName(input.Name)
	sc.SetGameMode(input.GameMode)
	sc.SetIntent(input.Intent)
	sc.SetSeason(input.Season)
	sc.SetVersion(input.Version)
	sc.SetMaxOnline(input.MaxOnline)
	sc.SetOnline(input.Online)
	sc.SetLevel(input.Level)
	sc.SetMod(input.Mod)
	sc.SetPvp(input.Pvp)
	sc.SetPassword(input.Password)
	sc.SetDedicated(input.Dedicated)
	sc.SetClientHosted(input.ClientHosted)
	sc.SetAllowNewPlayers(input.AllowNewPlayers)
	sc.SetServerPaused(input.ServerPaused)
	sc.SetFriendOnly(input.FriendOnly)
	sc.SetQueryVersion(input.QueryVersion)
	sc.SetCountry(input.Country)
	sc.SetContinent(input.Continent)
	sc.SetCountryCode(input.CountryCode)
	sc.SetCity(input.City)
	sc.SetRegion(input.Region)
	return sc
}

func (tc *TagCreate) SetTag(input *Tag) *TagCreate {
	tc.SetValue(input.Value)
	tc.SetOwnerID(input.OwnerID)
	return tc
}

func (uc *UserCreate) SetUser(input *User) *UserCreate {
	uc.SetUID(input.UID)
	uc.SetUsername(input.Username)
	uc.SetEmail(input.Email)
	uc.SetPassword(input.Password)
	uc.SetCreatedAt(input.CreatedAt)
	uc.SetUpdatedAt(input.UpdatedAt)
	return uc
}
