package dst

import (
	"github.com/dstgo/lobby/pkg/lobbyapi"
	"github.com/dstgo/lobby/server/data/ent"
)

func EntServerToServerInfo(server *ent.Server) ServerInfo {
	return ServerInfo{
		GUID:            server.GUID,
		RowID:           server.RowID,
		SteamID:         server.SteamID,
		SteamClanID:     server.SteamClanID,
		OwnerID:         server.OwnerID,
		SteamRoom:       server.SteamRoom,
		Session:         server.Session,
		Address:         server.Address,
		Port:            server.Port,
		Host:            server.Host,
		Platform:        server.Platform,
		ClanOnly:        server.ClanOnly,
		LanOnly:         server.LanOnly,
		Name:            server.Name,
		GameMode:        server.GameMode,
		Intent:          server.Intent,
		Season:          server.Season,
		Version:         server.Version,
		MaxOnline:       server.MaxOnline,
		Online:          server.Online,
		Mod:             server.Mod,
		Pvp:             server.Pvp,
		Password:        server.Password,
		Dedicated:       server.Dedicated,
		ClientHosted:    server.ClientHosted,
		AllowNewPlayers: server.AllowNewPlayers,
		ServerPaused:    server.ServerPaused,
		FriendOnly:      server.FriendOnly,
		Country:         server.Country,
		CountryCode:     server.CountryCode,
		Continent:       server.Continent,
		City:            server.City,
		Region:          server.Region,
		Level:           server.Level,
	}
}

func LobbyServerToServerInfo(server lobbyapi.Server) ServerInfo {
	return ServerInfo{
		GUID:            server.Guid,
		RowID:           server.RowId,
		SteamID:         server.SteamId,
		SteamClanID:     server.SteamClanId,
		OwnerID:         server.OwnerNetId,
		SteamRoom:       server.SteamRoom,
		Session:         server.Session,
		Address:         server.Address,
		Port:            server.Port,
		Host:            server.Host,
		Platform:        lobbyapi.PlatformDisplayName(server.Region, server.Platform),
		ClanOnly:        server.ClanOnly,
		LanOnly:         server.LanOnly,
		Name:            server.Name,
		GameMode:        server.GameMode,
		Intent:          server.Intent,
		Season:          server.Season,
		Version:         server.Version,
		MaxOnline:       server.MaxConnections,
		Online:          server.Connected,
		Mod:             server.Mod,
		Pvp:             server.Pvp,
		Password:        server.HasPassword,
		Dedicated:       server.IsDedicated,
		ClientHosted:    server.ClientHosted,
		AllowNewPlayers: server.AllowNewPlayers,
		ServerPaused:    server.ServerPaused,
		FriendOnly:      server.FriendOnly,
		Region:          server.Region,
		Tags:            server.Tags,
		Secondaries:     server.Secondaries,
	}
}

func LobbyServerToEntServer(server lobbyapi.Server) *ent.Server {
	return &ent.Server{
		GUID:            server.Guid,
		RowID:           server.RowId,
		SteamID:         server.SteamId,
		SteamClanID:     server.SteamClanId,
		OwnerID:         server.OwnerNetId,
		SteamRoom:       server.SteamRoom,
		Session:         server.Session,
		Address:         server.Address,
		Port:            server.Port,
		Host:            server.Host,
		Platform:        lobbyapi.PlatformDisplayName(server.Region, server.Platform),
		ClanOnly:        server.ClanOnly,
		LanOnly:         server.LanOnly,
		Name:            server.Name,
		GameMode:        server.GameMode,
		Intent:          server.Intent,
		Season:          server.Season,
		Version:         server.Version,
		MaxOnline:       server.MaxConnections,
		Online:          server.Connected,
		Mod:             server.Mod,
		Pvp:             server.Pvp,
		Password:        server.HasPassword,
		Dedicated:       server.IsDedicated,
		ClientHosted:    server.ClientHosted,
		AllowNewPlayers: server.AllowNewPlayers,
		ServerPaused:    server.ServerPaused,
		FriendOnly:      server.FriendOnly,
		Region:          server.Region,
	}
}
